name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: npm ci

      - name: Build & Export (static)
        env:
          # If you're hosting at https://username.github.io/party-games/
          NEXT_PUBLIC_PAGES_BASE_PATH: '/party-games'
          NEXT_PUBLIC_PAGES_ASSET_PREFIX: '/party-games/'
        run: |
          npm run build
          npm run export

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
